[package]
name = "pomody-desktop"
version = "0.2.0"
description = "Minimalist focus timer designed for deep work"
authors = ["Pomody Contributors"]
license = ""
repository = "https://github.com/EmanuelAngel/pomody"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pomody_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.6" }
tauri-plugin-log = "2"
